package us.careydevelopment.accounting.model;

public enum AssetAccountType {
    ACCOUNTS_RECEIVABLE, CURRENT_ASSETS, FIXED_ASSETS, INVENTORY, INVESTMENT, ACCUMULATED_DEPRECIATION,
    ACCUMULATED_AMORTIZATION, GOODWILL, LICENSES, BANK;
}

