package us.careydevelopment.accounting.model;

public enum AssetAccountType {
    ACCOUNTS_RECEIVABLE, CURRENT_ASSETS, FIXED_ASSETS, INVENTORY, INVESTMENT, ACCUMULATED_DEPRECIATION,
    ACCUMULATED_AMORTIZATION, GOODWILL, LICENSES, CASH_ON_HAND, CHECKING_ACCOUNT, MONEY_MARKET,
    RENTS_HELD_IN_TRUST, SAVINGS_ACCOUNT, TRUST_ACCOUNT;;
}

