package us.careydevelopment.accounting.model;

public enum CompanyTaxForm {
    SOLE_PROPRIETOR_FORM_1040, PARTNERSHIP_FORM_1065, SMALL_BUSINESS_FORM_1120S, CORPORATION_FORM_1120,
    NONPROFIT_FORM_990, LIMITED_LIABILITY, OTHER;
}
