package us.careydevelopment.accounting.model;

public enum EquityAccountType {
    COMMON_STOCK, OPENING_BALANCE_EQUITY, OWNERS_EQUITY, PAID_IN_CAPITAL, PARTNER_CONTRIBUTIONS,
    PARTNER_DISTRIBUTIONS, PARTNERS_EQUITY, PREFERRED_STOCK, RETAINED_EARNINGS, TREASURY_STOCK,
    OWNERS_DRAW, NET_INCOME;
}
