package us.careydevelopment.accounting.model;

public enum ExpenseAccountType {
    MARKETING, COST_OF_GOODS_SOLD, AUTO, BAD_DEBTS, BANK_CHARGES, CHARITABLE_CONTRIBUTIONS, COST_OF_LABOR,
    DUES_AND_SUBSCRIPTIONS, ENTERTAINMENT, MEALS, EQUIPMENT_RENTAL, FINANCE_COSTS, INSURANCE, INTEREST_PAID,
    PROFESSIONAL_FEES, OFFICE_ADMIN_EXPENSES, OTHER, MISCELLANEOUS_SERVICE, PAYROLL_EXPENSES, PAYROLL_TAX_EXPENSES,
    PAYROLL_WAGE_EXPENSESS, PROMOTIONAL_MEALS, RENT, MAINTENANCE, SHIPPING, SUPPLIES, TAXES, TRAVEL_MEALS,
    UNAPPLIED_PAYMENT, UTILITIES, AMORTIZATION, DEPRECIATION, EXCHANGE, FUEL, HOME_OFFICE, HOMEOWNER_RENTAL_INSURANCE,
    MORTGAGE_INTEREST_HOME_OFFICE, OTHER_HOME_OFFICE_EXPENSE, OTHER_VEHICLE_EXPENSE, PARKING_AND_TOLLS,
    PENALTIES_AND_SETTLEMENTS, PROPERTY_TAX_HOME_OFFICE, RENT_HOME_OFFICE, MAINTENANCE_HOME_OFFICE,
    UTILTIES_HOME_OFFICE, VEHICLE, VEHICLE_INSURANCE, VEHICLE_LEASE, VEHICLE_LOAN, VEHICLE_LOAN_INTEREST,
    VEHICLE_REGISTRATION, VEHICLE_REPAIRS, WASH_AND_ROAD_SERVICES;

}
